sudo: required
services:
  - docker

before_install:
  - docker build -t avidocker001/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true avidocker001/docker-react npm run test -- --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "avidocker-react-app"
  env: "Avidockerreactapp-env"
  bucket_name: "elasticbeanstalk-ap-south-1-261643621708"
  bucket_path: "avidocker-react-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY